# Generated by Django 3.0.5 on 2020-04-19 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title.', max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the article.', max_length=1000)),
                ('body', models.TextField(help_text='Add an article here. Use html tags.')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Choose the status of an article from the drop-list', max_length=10)),
                ('author', models.ForeignKey(help_text='Article author (choose username).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_code', models.CharField(help_text='Add here code to use in the articles', max_length=10)),
                ('image_small_url', models.URLField(help_text='Add here image small size url')),
                ('image_middle_url', models.URLField(help_text='Add here image middle size url')),
                ('image_original_url', models.URLField(help_text='Add here image original size url')),
                ('image_text', models.TextField(help_text='Enter a brief description of the image.', max_length=1000)),
                ('article_head', models.BooleanField(help_text="Check this, if image is article's main image.")),
                ('slideshow', models.BooleanField(help_text='Check this, if image is included in slideshow')),
                ('article', models.ForeignKey(help_text='Choose article for the image', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Article')),
            ],
        ),
    ]
