# Generated by Django 3.0.5 on 2020-04-19 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Add e-mail here', max_length=254)),
                ('body', models.TextField(help_text='Add your comment here')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to deactivate comment')),
                ('article', models.ForeignKey(help_text='Comment on article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Comments', to='articles.Article')),
                ('user', models.ForeignKey(help_text='User who posted this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
