# Generated by Django 3.0.5 on 2020-04-18 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20200417_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_code', models.CharField(help_text='Add here code to use in articles', max_length=10)),
                ('image_small_url', models.URLField(help_text='Add here image small size url')),
                ('image_middle_url', models.URLField(help_text='Add here image middle size url')),
                ('image_original_url', models.URLField(help_text='Add here image original size url')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(help_text='Article author (choose username).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='Add an article here. Use html tags.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Choose the status of an article from the drop-list', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the article.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Article title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='pict_url',
            field=models.ForeignKey(help_text='Add here image code to be used it article summary', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Image'),
        ),
    ]
