# Generated by Django 3.0.5 on 2020-04-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200420_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_created',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='comment_article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='is_active',
        ),
    ]
