# Generated by Django 3.0.5 on 2020-04-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200422_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('topo', 'Topo'), ('tip', 'Tip'), ('tour', 'Tour')], default='article', help_text='Choose type of the article from the drop-list', max_length=20),
        ),
    ]
