# Generated by Django 3.0.5 on 2020-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200422_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_middle_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_original_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_small_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image_middle',
            field=models.ImageField(blank=True, upload_to='media/images/middle', verbose_name='Middle image'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_orig',
            field=models.ImageField(blank=True, upload_to='media/images/orig', verbose_name='Original image'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_small',
            field=models.ImageField(blank=True, upload_to='media/images/small', verbose_name='Small image'),
        ),
    ]
