# Generated by Django 3.0.5 on 2020-04-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200422_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_middle',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_orig',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_small',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_code',
            field=models.CharField(help_text='Add here code to use in the articles', max_length=12),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_text',
            field=models.CharField(blank=True, help_text='Alt text.', max_length=255),
        ),
    ]
