# Generated by Django 3.0.5 on 2020-04-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='slideshow',
            new_name='gallery',
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('topo', 'Topo'), ('tip', 'Tip'), ('tour', 'Tour'), ('gallery', 'Gallery')], default='article', help_text='Choose type of the article from the drop-list', max_length=20),
        ),
    ]
